# This is a basic workflow to help you get started with Actions

name: Spinnaker Pre Install
env:
  ArgoCD_VERSION: 1.26.6
  NEW_REGISTRY_URL: "http://docker.io/lizeyang123"

on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: rsync images
      run: |
        docker pull ghcr.io/dexidp/dex:v2.27.0
        docker pull quay.io/argoproj/argocd:v2.1.3
        
        docker tag ghcr.io/dexidp/dex:v2.27.0  ${NEW_REGISTRY_URL}/dex:v2.27.0
        docker tag quay.io/argoproj/argocd:v2.1.3  ${NEW_REGISTRY_URL}/argocd:v2.1.3
        
        docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASSWD}} ${NEW_REGISTRY_URL}
        docker push ${NEW_REGISTRY_URL}/dex:v2.27.0
        docker push ${NEW_REGISTRY_URL}/argocd:v2.1.3
